version: '3.7'

services:
  binance-bot:
    container_name: binance-bot-dev
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    networks:
      - internal
    volumes:
      - ./config:/srv/config
      - ./app:/srv/app
      - ./public:/srv/public
      - ./migrations:/srv/migrations
      - ./scripts:/srv/scripts
    env_file:
      - .env
    restart: unless-stopped
    environment:
      #      - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_REDIS_HOST=binance-redis
      - BINANCE_REDIS_PORT=6379
      - BINANCE_TRADINGVIEW_HOST=tradingview
      - BINANCE_TRADINGVIEW_PORT=8082
    ports:
      - '8080:80'
    logging:
      driver: 'json-file'
      options:
        max-size: '1G'

  tradingview:
    container_name: tradingview
    build:
      context: ./tradingview
    networks:
      - internal
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # https://docs.python.org/3/howto/logging.html#logging-levels
      - BINANCE_TRADINGVIEW_LOG_LEVEL=ERROR
      - BINANCE_TRADINGVIEW_PORT=8082
    ports:
      - '8082:8082'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  binance-redis:
    container_name: binance-redis-dev
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    # sysctls:
    #   #vm.swappiness: 0
    #   net.ipv4.tcp_sack: 1
    #   net.ipv4.tcp_timestamps: 1
    #   net.ipv4.tcp_window_scaling: 1
    #   net.ipv4.tcp_congestion_control: cubic
    #   net.ipv4.tcp_syncookies: 1
    #   net.ipv4.tcp_tw_reuse: 1
    #   net.ipv4.tcp_max_syn_backlog: 3240000
    #   net.core.somaxconn: 65536
    restart: unless-stopped
    networks:
      - internal
    ulimits:
      memlock: -1
    ports:
      - '6379:6379'
    volumes:
      - dragonfly_data:/data
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: dragonfly --hz=1000 --cluster_mode=emulated --lock_on_hashtags

  binance-mongo:
    container_name: binance-mongo-dev
    image: mongo:7.0.4-jammy
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

  binance-mongo-express:
    container_name: binance-mongo-express-dev
    image: mongo-express:1.0
    restart: unless-stopped
    networks:
      - internal
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=binance-mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

networks:
  internal:
    driver: bridge

volumes:
  dragonfly_data:
  mongo_data:
